# Generated by Django 3.0.8 on 2020-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
