# Generated by Django 3.0.8 on 2020-12-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_approved',
            new_name='is_batchCoordinator',
        ),
    ]
