# Generated by Django 3.0.8 on 2020-08-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0007_auto_20200807_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=40)),
                ('organization_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('date_join', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professionalInfo.Organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile')),
            ],
        ),
    ]
