# Generated by Django 3.0.8 on 2020-08-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workingSkills', '0001_initial'),
        ('userProfile', '0007_auto_20200807_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudiesUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=100)),
                ('domain', models.ManyToManyField(to='workingSkills.Domain')),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyAndResearch.Country')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile')),
                ('study_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workingSkills.Domain')),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyAndResearch.HigherStudiesUniversity')),
            ],
        ),
    ]
