# Generated by Django 3.0.8 on 2020-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0007_auto_20200807_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsAndTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_and_technology', models.CharField(max_length=40)),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=40)),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
            ],
        ),
    ]
