# Generated by Django 3.0.8 on 2020-09-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingSkills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='toolsandtechnology',
            name='profile',
        ),
    ]
