# Generated by Django 3.0.8 on 2020-07-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_country_domain_higherstudies_higherstudiesuniversity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=40)),
                ('organization_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsAndTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_and_technology', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('date_join', models.DateField()),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userProfile.Organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.Profile')),
            ],
        ),
    ]
