# Generated by Django 3.0.8 on 2020-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_environment_organization_professionalinfo_toolsandtechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('domain', models.ManyToManyField(to='userProfile.Domain')),
                ('environment', models.ManyToManyField(to='userProfile.Environment')),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
                ('tools_and_technology', models.ManyToManyField(to='userProfile.ToolsAndTechnology')),
            ],
        ),
    ]
