# Generated by Django 3.0.8 on 2020-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20200715_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_mail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
