# Generated by Django 3.0.8 on 2020-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20200807_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_of',
            new_name='user',
        ),
    ]
