# Generated by Django 3.0.8 on 2020-08-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20200808_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='profile_of',
        ),
    ]
