# Generated by Django 3.0.8 on 2020-08-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20200812_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_of',
            new_name='user',
        ),
    ]
