# Generated by Django 3.0.8 on 2020-12-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_additionalmail_facebook_github_linkedin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_batchCoordinator',
        ),
    ]
