# Generated by Django 3.0.8 on 2020-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workingSkills', '0001_initial'),
        ('userProfile', '0007_auto_20200807_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('domain', models.ManyToManyField(to='workingSkills.Domain')),
                ('environment', models.ManyToManyField(to='workingSkills.Environment')),
                ('profile', models.ManyToManyField(to='userProfile.Profile')),
                ('tools_and_technology', models.ManyToManyField(to='workingSkills.ToolsAndTechnology')),
            ],
        ),
    ]
