# Generated by Django 3.0.8 on 2020-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_createproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='project_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
